name: Deploy MultiDocker
on:
  push:
    branches:
      - master # άλλαξέ το σε main αν το repo σου έχει main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Test Image
        run: docker build -t sanagno/react-test -f Dockerfile.dev .

      - name: Run Tests
        run: docker run -e CI=true sanagno/react-test npm test

      - name: Build Production Images
        run: |
          docker build -t sanagno/multi-client-10-14 ./client
          docker build -t sanagno/multi-nginx-10-14 ./nginx
          docker build -t sanagno/multi-server-10-14 ./server
          docker build -t sanagno/multi-worker-10-14 ./worker

      - name: Push Images to Docker Hub
        run: |
          docker push sanagno/multi-client-10-14
          docker push sanagno/multi-nginx-10-14
          docker push sanagno/multi-server-10-14
          docker push sanagno/multi-worker-10-14

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-gh
          environment_name: Multigh-env
          existing_bucket_name: elasticbeanstalk-eu-north-1-923445559289
          region: eu-north-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip