name: Deploy Frontend
on:
  push:
    branches:
      - master # ή main αν το default branch σου λέγεται main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # 1. Σύνδεση στο Docker Hub
      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      # 2. Build του test image
      - name: Build Test Image
        run: docker build -t sanagno/react-test -f Dockerfile.dev .

      # 3. Εκτέλεση των tests
      - name: Run Tests
        run: docker run -e CI=true sanagno/react-test npm test

      # 4. Build του Production Image (React + Nginx)
      - name: Build Production Image
        run: docker build -t sanagno/docker-react .

      # 5. Push του production image στο Docker Hub
      - name: Push to Docker Hub
        run: docker push sanagno/docker-react

      # 6. Δημιουργία zip για το Elastic Beanstalk
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      # 7. Deployment στο AWS Elastic Beanstalk
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-gh
          environment_name: Multigh-env
          existing_bucket_name: elasticbeanstalk-eu-north-1-923445559289
          region: eu-north-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip